name: GitHub Cleanup

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  cleanup-releases:
    runs-on: ubuntu-latest
    name: Clean up old releases
    steps:
      - uses: actions/checkout@v4
      - uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 2
          keep-old-minor-releases: false
          keep-old-minor-releases-count: 1
