name: Build & Upload
on:
  workflow_dispatch:

jobs:
  build_androidApk:
    name: Build Release APK
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases
    steps:
      - uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          cache: true

      - name: Cache Pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Microg
        run: |
          mkdir -p build/app/outputs/flutter-apk
          gh release download --repo MorpheApp/MicroG-RE --pattern "*.apk" --dir build/app/outputs/flutter-apk

      - name: Build Release APK with mise
        env:
          SECRETS_ENVS_BASE64: ${{ secrets.ENVS }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: mise run build:release

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/*/*/*.apk"
          allowUpdates: true
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "RDmanager v1.0.${{ github.run_number }}"

      - name: ntfy-notifications
        if: ${{ always() && env.NTFY_URL != '' }}
        env:
          NTFY_URL: ${{ secrets.NTFY_URL }}
        uses: niniyas/ntfy-action@master
        with:
          url: ${{ env.NTFY_URL }}
          topic: ${{ secrets.NTFY_TOPIC }}
          title: "RDmanager Build #${{ github.run_number }}: ${{ job.status }}"
          details: "Build  #${{ github.run_number }}: ${{ job.status }} - v1.0.${{ github.run_number }}"
