name: Build & Upload
on:
  workflow_dispatch:

jobs:
  build_androidApk:
    name: Build Release APK
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-java@main
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      # 4. Cache Pub Dependencies
      # Speeds up 'flutter pub get' by storing the package cache
      - name: Cache Pub dependencies
        uses: actions/cache@main
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # 5. Install Dependencies
      - run: flutter pub get

      # 6. Configure Keystore & Secrets
      # securely decodes the keystore and writes key.properties
      - name: Setup Signing Configuration
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/keystore.jks
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=${{ github.workspace }}/android/keystore.jks" >> android/key.properties
          echo "${{ secrets.SECRETS_ENVS_BASE64 }}" | base64 -d > lib/secrets.dart
      - name: Microg
        run: |
            gh release download --repo MorpheApp/MicroG-RE --pattern "*.apk" --dir build/app/*/*/*

      - name: Build APK
        run: flutter build apk --release --target-platform  android-arm64 --build-name "RDmanager v1.0.${{ github.run_number }}"
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/*/*/*.apk"
          allowUpdates: true
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "RDmanager v1.0.${{ github.run_number }}"

      # - name: ntfy-notifications
      #   uses: niniyas/ntfy-action@master
      #   with:
      #     url: ${{ secrets.NTFY_URL }}
      #     topic: ${{ secrets.NTFY_TOPIC }}
      #     title: "RDmanager Build #${{ github.run_number }}: ${{ job.status }}"
      #     details: "Build  #${{ github.run_number }}: ${{ job.status }} - v1.0.${{ github.run_number }}"
